import Head from "next/head";
import styles from "../styles/Home.module.css";
import Cards from "../components/cards/cards";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Christian Handbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Christian Handbook</h1>

        <p className={styles.description}>Get started by searching person</p>
        <Cards />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" Mathetes "}
        </a>
      </footer>
    </div>
  );
}
